site_name: Go语言学习 - cyent笔记
site_description: 关于Go语言学习，包含许多个人理解
site_author: cyent
site_url: https://cyent.github.io/golang/

repo_name: 'cyent/golang'
repo_url: 'https://github.com/cyent/golang'

theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'

extra:
  social:
    - type: github
      link: https://github.com/cyent
  search:
    language: 'jp'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg
        #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
        #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
        #emoji_generator: !!python/name:pymdownx.emoji.to_alt
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

extra_javascript:
    - 'js/extra.js'
    - 'js/baidu-tongji.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

pages:
    - 一. 介绍: index.md
    - 二. 代码组织:
        - 1. workspace: organization/workspace.md
        - 2. GOPATH: organization/gopath.md
        - 3. import path: organization/importpath.md
        - 4. hello world: organization/helloworld.md
        - 5. 第一个library: organization/firstlib.md
        - 6. 内置的轻量级测试框架: organization/test.md
    - 三. 基础:
        - 1. Packages: basic/packages.md
        - 2. Imports: basic/imports.md
        - 3. 导出名: basic/exportname.md
        - 4. 函数: basic/function.md
        - 5. 变量:
            - 5.1. 声明: basic/variable_declare.md
            - 5.2. 作用域: basic/variable_affect.md
        - 6. 常量: basic/const.md
        - 7. 数据类型:
            - 7.1. 介绍: basic/type_main.md
            - 7.2. 默认值: basic/type_default.md
            - 7.3. 类型转换: basic/type_change.md
            - 7.4. 类型推导: basic/type_guess.md
            - 7.5. 自定义类型: basic/type_custom.md
    - 四. 流控制:
        - 1. for: flow/for.md
        - 2. if: flow/if.md
        - 3. switch: flow/switch.md
        - 4. defer: flow/defer.md
    - 五. 数据类型:
        - 1. pointer: datatype/pointer.md
        - 2. struct:
            - 2.1. 声明: datatype/struct_main.md
            - 2.2. 导出名: datatype/struct_export.md
            - 2.3. struct指针: datatype/struct_pointer.md
            - 2.4. literal: datatype/struct_literal.md
            - 2.5. 匿名struct: datatype/struct_anon.md
            - 2.6. 接口作为struct元素: datatype/struct_interface_element.md
            - 2.7. struct作为struct的元素: datatype/struct_struct_element.md
            - 2.8. 空struct: datatype/struct_empty.md
        - 3. array和slice:
            - 3.1. 介绍与比较: datatype/arr_sli_main.md
            - 3.2. len()与cap(): datatype/arr_sli_len_cap.md
            - 3.3. 下标: datatype/arr_sli_index.md
            - 3.4. 深入理解: datatype/arr_sli_key.md
            - 3.5. nil: datatype/arr_sli_nil.md
            - 3.6. make: datatype/arr_sli_make.md
            - 3.7. slice嵌套: datatype/arr_sli_nest.md
            - 3.8. slice扩容: datatype/arr_sli_expand.md
            - 3.9. append添加元素: datatype/arr_sli_append.md
            - 3.10. copy复制元素: datatype/arr_sli_copy.md
            - 3.11. 空接口对切片的影响: datatype/arr_empty_interface.md
        - 4. map:
            - 4.1. 声明: datatype/map_main.md
            - 4.2. nil map: datatype/map_nil.md
            - 4.3. key和value可以用struct: datatype/map_struct.md
            - 4.4. literal: datatype/map_literal.md
            - 4.5. 检索、添加和修改元素: datatype/map_get_insert_update.md
            - 4.6. delete删除元素: datatype/map_delete.md
        - 5. 函数值:
            - 5.1. 介绍: datatype/funcvalue_main.md
            - 5.2. 函数作为参数传递给另一个函数: datatype/funcvalue_parameter.md
            - 5.3. 用途1-回调函数: datatype/funcvalue_callback.md
            - 5.4. 用途2-闭包: datatype/funcvalue_closure.md
    - 六. 方法与接口:
        - 1. 概念汇总: method/overview.md
        - 2. 方法:
            - 2.1. 声明: method/method_main.md
            - 2.2. 指针receiver: method/method_receiver.md
        - 3. 接口:
            - 3.1. 什么是接口: method/interface_main.md
            - 3.2. 接口语法: method/interface_syntax.md
            - 3.3. Why interface: method/interface_why.md
            - 3.4. 接口和面向对象的关系: method/interface_oo.md
            - 3.5. 应用场景: method/interface_application.md
            - 3.6. 传入和传出参数要带上: method/interface_argv.md
            - 3.7. 接口receiver参数类型不会自动转换: method/interface_receiver.md
            - 3.8. 各种实现: method/interface_implement.md
            - 3.9. nil interface: method/interface_nil.md
            - 3.10. 空接口: method/interface_empty.md
            - 3.11. 类型断言: method/interface_assertion.md
            - 3.12. type switch: method/interface_typeswitch.md
            - 3.13. Stringer: method/interface_stringer.md
            - 3.14. 函数的传入传出参数来实现接口: method/interface_argv_interface.md
            - 3.15. 实现接口的多种方法汇集: method/interface_implement_interface.md
            - 3.16. error: method/interface_error.md
            - 3.17. 接口作为struct的元素: method/interface_struct_element.md
            - 3.18. 深入理解: method/interface_deep.md
            - 3.19. 从无到有逐步理解面向对象和接口: method/interface_01.md
    - 七. 反射:
        - 1. 介绍: reflect/main.md
        - 2. reflect(反射包):
            - 2.1. Type和Value: reflect/pkg_type_value.md
            - 2.2. TypeOf()与ValueOf(): reflect/pkg_typeof_valueof.md
        - 3. fmt: reflect/fmt.md
        - 4. 法则1: reflect/law1.md
        - 5. 法则2: reflect/law2.md
        - 6. 法则3: reflect/law3.md
    - 八. 协程:
        - 1. 创建协程(go关键字): goroutine/main.md
        - 2. channel:
            - 2.1. 基本使用: goroutine/channel_main.md
            - 2.2. buffer: goroutine/channel_buffer.md
            - 2.3. close: goroutine/channel_close.md
            - 2.4. 结合select-case: goroutine/channel_select.md
            - 2.5. 读写类型: goroutine/channel_rw.md
        - 3. 同步(sync):
            - 3.1. 参考资料: goroutine/sync_reference.md
            - 3.2. 互斥锁(Mutex): goroutine/sync_mutex.md
            - 3.3. 读写锁(RWMutex): goroutine/sync_rwmutex.md
            - 3.4. WaitGroup: goroutine/sync_waitgroup.md
            - 3.5. 条件变量(Cond): goroutine/sync_cond.md
    - 九. 其他:
        - 1. 字符串处理: other/string.md
        - 2. range: other/range.md
        - 3. 并发、事件驱动等: other/concurrent.md
        - 4. 位运算: other/binary_operation.md
        - 5. 循环、迭代、遍历、递归的区别: other/loop_iterate_traversal_recursion.md
        - 6. go和python的比较: other/go_python.md
        - 7. 面向对象: other/oo.md
        - 8. nil: other/nil.md
        - 9. make: other/make.md
        - 10. 枚举: other/enum.md
        - 11. Readers: other/readers.md
        - 12. 编码风格: other/style.md
        - 13. new: other/new.md
        - 14. 多进程、多线程、协程比较:
            - 14.1. CPU占用率比较: other/ptr_cpu.md
            - 14.2. 屏幕输出比较: other/ptr_stdout.md
        - 15. C语言的fork: other/fork.md
        - 16. 查看系统环境runtime: other/runtime.md
        - 17. 构造方法: other/constructor.md
    - 十. 附录:
        - 1. 文档: appendix/doc.md
        - 2. 编码规范: appendix/code.md
        - 3. 命令行工具:
            - 3.1. go get: appendix/cli_go_get.md
    - 十一. 联系方式: contact.md
